// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one

INSERT INTO posts
  (id,created_at,updated_at,title,url,description,published_at,feed_id)
VALUES
  (
   $1, $2, $3, $4, $5, $6, $7, $8 
  )

RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT
  posts.id, posts.created_at, posts.updated_at, title, posts.url, description, published_at, feed_id, feeds.id, feeds.name, feeds.url, feeds.created_at, feeds.updated_at, user_id, last_fetched_at, users.id, users.name, users.created_at, users.updated_at
FROM
  posts
  LEFT JOIN feeds ON posts.feed_id = feeds.id
  LEFT JOIN users ON feeds.user_id = users.id
WHERE
  users.name = $1
ORDER BY
  posts.published_at DESC
LIMIT
  $2
`

type GetPostsForUserParams struct {
	Name  string
	Limit int32
}

type GetPostsForUserRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Url           string
	Description   sql.NullString
	PublishedAt   sql.NullTime
	FeedID        uuid.UUID
	ID_2          uuid.NullUUID
	Name          sql.NullString
	Url_2         sql.NullString
	CreatedAt_2   sql.NullTime
	UpdatedAt_2   sql.NullTime
	UserID        uuid.NullUUID
	LastFetchedAt sql.NullTime
	ID_3          uuid.NullUUID
	Name_2        sql.NullString
	CreatedAt_3   sql.NullTime
	UpdatedAt_3   sql.NullTime
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.ID_2,
			&i.Name,
			&i.Url_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.UserID,
			&i.LastFetchedAt,
			&i.ID_3,
			&i.Name_2,
			&i.CreatedAt_3,
			&i.UpdatedAt_3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
